### ISSUE TITLE
Trending Movie Collection not respecting date limit

### ISSUE THREAD

**Issue by Sdhb1** [agregarr/agregarr#253]
### Description

My trending movies collection is pulling in Avatar Fire and Ash, which releases in March next year. Since the collection date limit is set to "1" day only, I think that title  should not be pulling in. Same with Badlands. Seems like agregarr might not be respecting collection date limits consistantly. 

![Image](https://github.com/user-attachments/assets/498f2539-b493-41a9-9b61-f10012059649)
![Image](https://github.com/user-attachments/assets/5a9ddc2a-608a-4c48-8745-e26d86e7baeb)

### Version

858f7934a602bb2b9b528c3e2e237b86476d3394

### Steps to Reproduce

Add collection with date limit and allow sync. 

### Logs

```shell

```

**Comment by Sdhb1** [comment]
@samohtxotom  I'm still seeing this issue. Can we re-open?  These collections are set to 1 day future limit, but they are from farther in the future. TY

![Image](https://github.com/user-attachments/assets/6e02dd6b-6c97-4998-bbbe-561bc966687f)

**Comment by agregarr** [comment]
should be working now?

**Comment by Sdhb1** [comment]
@samohtxotom  - I'm afraid not. Still seeing future dated movies in this collection.

<img width="981" height="219" alt="Image" src="https://github.com/user-attachments/assets/4bc3b03d-cb98-41bd-8538-cd71eb509645" />

**Comment by Sdhb1** [comment]
Unfortunately it seems to still be a problem. Several movies appear with overlays indicating release is in the the far future. Collection settings are set to 1 day future only. Any ideas?

Side note, how can the user indicate to not show any future dated movies in this collection? It seems like the minimum number is 1. Entering 0 or blank results in resetting to 100.

<img width="1401" height="233" alt="Image" src="https://github.com/user-attachments/assets/62e5b79f-76ca-4857-9bd8-9bb78db4eb79" />

**Comment by Sdhb1** [comment]
@samohtxotom Do you need logs for this? Ty
