### ISSUE TITLE
Collection reordering is not fixed - still get randomised order on syncs

### ISSUE THREAD

**Issue by Tronicgg** [agregarr/agregarr#55]
Tried latest version, still having exactly the same issue: Agregarr randomises collection order on every sync. No matter what. If I try to change order of collections within Plex it now simply refuses to change anything. Within Agregarr I can change order, but this order is ignored on syncs and just pushes some random order to Plex.

Edit: Seems to be a little worse than before as in I cannot change the order on Agregarr anyome. I drag and drop and immediately it resorts back to whatever order it wants. Example: (https://youtu.be/nN3dTiKHD0o) + behaviour on Plex's side: (https://youtu.be/81QlEdkDCuc)

**Comment by agregarr** [comment]
So the reordering in Plex, that is just a Plex thing, it has always been like that, you can't move an item to the top position - look at the network logs you will see it is making the call `/hubs/sections/1/manage/custom.collection.1.39695/**move?after=**custom.collection.1.38612`, you cannot move an item to the top in their UI because there is no item to move it after. as for why its is not working in agregarr, that is very strange as it should now be verifying the position and correcting it if it fails, so it must be failing repeatedly, and at the end we run discovery, which is why it would be resetting back to the top position. also looking at your videos it appears it is not random at all, and simply that the top two positions are incorrect? can you please confirm that?

**Comment by Tronicgg** [comment]
So there are two issues: the one I show on the vids where Agregarr simply refuses to switch top two items. Second issue: agregarr randomises order on every sync. 

As it stands right now the behaviour is as follows:

On Agregarr side - I reorder collections to my liking. Hit sync. After sync has finished the order is messed up on Agregarr. So in turn it messes it up on Plex. Here's a vid: (https://youtu.be/XYyxl0fq_6k)

Hope this helps better explain the issue.

**Comment by agregarr** [comment]
okay yeah that is very messed up, can you send me the logs file please?

<img width="967" height="230" alt="Image" src="https://github.com/user-attachments/assets/5f3ff32c-d7cd-4291-8e63-ea50f2f63904" />

**Comment by Tronicgg** [comment]
Is it fine to publish the log here publicly?

**Comment by agregarr** [comment]
probably not they have your plex token and api key for your services, you can DM them to me on discord if you want username is samohtxotom, or on reddit u/GoneBushM8

**Comment by Tronicgg** [comment]
Will do tomorrow.

Thanks.

**Comment by Tronicgg** [comment]
Log sent through reddit.

**Comment by agregarr** [comment]
Received, I wonder if this is yet another issue with the Plex hub reordering mechanism on Plex's side, if you remove two collections from you library 5, does that work? because I can see in the logs it is reordering all of them but 1, and then it fails and retries, but always fails, so the limit for their basic reordering mightbe 27 collections or something (this is a backend issue, probably could be partially solved by mapping out our reordering to minimise moves)

**Comment by king8084** [comment]
Some annoying thing happening with me

**Comment by Tronicgg** [comment]
> Received, I wonder if this is yet another issue with the Plex hub reordering mechanism on Plex's side, if you remove two collections from you library 5, does that work? because I can see in the logs it is reordering all of them but 1, and then it fails and retries, but always fails, so the limit for their basic reordering mightbe 27 collections or something (this is a backend issue, probably could be partially solved by mapping out our reordering to minimise moves)

Tried removing two on library 5 as suggested, same issue. Random order on every sync. :(

**Comment by vchittar** [comment]
@agregarr 

You might have to store the order state manually and after the sync is done, replace the ordering from plex with the one you have stored

**Comment by agregarr** [comment]
its a terrible system to work with I actually submitted a bug report to Plex because it's that bad, and you can easily break it in the Plex UI yourself https://forums.plex.tv/t/plex-home-recommended-reordering-breaks-after-certain-number-of-moves/930742

nonetheless I think we should still be able to make it work, I can get back to focusing on this now (sorry I was just sick of dealing with the damn reordering lol)

**Comment by agregarr** [comment]
this should fix it if not please comment here and I;ll reopen the issue

**Comment by Tronicgg** [comment]
The issue persists in 1.3.1 unfotunately. Same exact behaviour.

**Comment by agregarr** [comment]
This might be leftover data pre-patch, can you check you don't have any corrupted items, sometimes this is picked up by the missing collections detection and then you can just press the clean button, but sometimes not. To check go to all collections view, and scroll down the list and look at the first badge for any items that don't have either the collection specific badge (e.g. Trakt - Trending), the Pre-Existing Collection badge, or the Plex Default badge. From memory is just said Items: 50. To fix you can stop agregarr and delete it manually from settings.json, or delete and recreate the collection in Plex and the missing items will pick it up and you can just press clean

**Comment by Tronicgg** [comment]
Not sure I follow you, but all my collections under "All Collections" have either the collection specific badge, the Pre-Existing Collection badge, or the Plex Default badge. Unsure what to look for.

**Comment by Tronicgg** [comment]
Ok, I’ve been testing for a couple days and this seems to be fixed. I will post if something changes, but for the time being thank you very much for the help and the fix.

**Comment by agregarr** [comment]
thanks for letting me know
